name: minerva_analysis
channels:
  - conda-forge
dependencies:
  - appdirs
  - flask=2.2.2
  - flask-sqlalchemy=3.0.2
  - itsdangerous=2.1.2
  - jinja2
  - numpy
  - ome-types=0.3.3
  - orjson
  - pandas
  - pillow=8.1
  - pip
  - pyinstaller
  - python=3.9.15
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - tifffile=2021.4.8
  - waitress
  - werkzeug=2.2.2
  - zarr=2.10

  - pip:
      - opencv-python==4.7.0.68
      - imagecodecs[all]
      - xmlschema
      - pydantic == 1.10.10

