name: minerva_analysis
channels:
  - conda-forge
dependencies:
  - appdirs
  - flask
  - flask-sqlalchemy
  - itsdangerous
  - jinja2
  - matplotlib
  - numpy
  - ome-types
  - orjson
  - pandas
  - pillow
  - pip
  - pyinstaller
  - python=3.13
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - tifffile
  - waitress
  - uv
  - werkzeug
  - zarr
  - pip:
      - -e .[jupyter,dev]
      - opencv-python>=4.12
      - xmlschema
