name: visinity
channels:
  - conda-forge
dependencies:
  - python=3.9
  - appdirs
  - Flask=2.3.2
  - flask-sqlalchemy=3.0.2
  - hdbscan=0.8.28
  - imagecodecs=2022.2.22
  - llvmlite=0.39.1
  - joblib=1.1.0
  - matplotlib
  - numba
  - numpy
  - orjson
  - pandas
  - pillow=8.1.1
  - requests
  - scikit-learn=1.1.2
  - scikit-image
  - scipy
  - tifffile=2021.4.8
  - waitress
  - zarr=2.10.1
  - pyinstaller
  - pip
  - pip:
      - elementpath==2.3.2
      - pycave==3.1.3
      - pydantic==1.10.2
      - numpy-indexed
      - ome-types==0.2.9
      - opencv-python
      - umap-learn
      - xmlschema==1.8.0
