name: dockerhub

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clean up the release tag test
        id: cleantag
        run: |
          tag=$(echo ${{ github.event.release.tag_name }} | tr -d v)
          echo ${{ env.BRANCH }}:${tag%"_${{ env.BRANCH }}"} 
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ${{steps.cleantag.outputs.tag}}
#       -
#         name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}
