name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Branch Names
        id: branch-names
        uses: tj-actions/branch-names@v9.0.2
        with:
          strip_tag_prefix: 'v'
      - name: Version String
        shell: bash -l {0}
        run: |
          CLEAN_VERSION="${{ steps.branch-names.outputs.tag }}"
          CLEAN_VERSION="${CLEAN_VERSION//./_}"
          echo "VERSION_STRING=$CLEAN_VERSION" >> $GITHUB_ENV
      - name: Creating Private Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node and Webpack
        run: |
          cd minerva_analysis
          cd client
          npm install
          npm run start
          rm -r node_modules
          cd ..
          cd ..
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: requirements.yml
          activate-environment: minerva_analysis
          auto-activate-base: false
          use-mamba: true
      # - name: Package Windows
      #   if: startsWith(matrix.os,'windows')
      #   shell: cmd /C CALL {0}
      #   run: |
      #     package_win.bat
      # - name: Rename Windows
      #   if: startsWith(matrix.os,'windows')
      #   shell: bash -l {0}
      #   run: |
      #     ls dist/
      #     mv dist/minerva_analysis_windows.exe "dist/Gater_Windows_${{github.event.client_payload.version}}.exe"
      #     ls dist/
      - name: Package Mac
        if: startsWith(matrix.os,'mac')
        shell: bash -l {0}
        run: |
          ./package_mac.sh "Gater_Mac_${{ env.VERSION_STRING }}"
      - name: Rename Mac
        if: startsWith(matrix.os,'mac')
        shell: bash -l {0}
        run: |
          cd dist
          zip -r "Gater_Mac_${{ env.VERSION_STRING }}.zip" "Gater_Mac_${{ env.VERSION_STRING }}"
          rm -rf "Gater_Mac_${{ env.VERSION_STRING }}"
      # - name: Release
      # uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      # with:
      #   files: |
      #     dist/*
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    